"""Derive visible glyph bounds from the locally exported retail HUD atlas."""
from pathlib import Path
from PIL import Image
from prepare_skip_prompt import characters, root

def main():
    glyphs = characters(0x29CD3)  # revision-pinned hud_action_font_z export
    atlas = Image.open(root / 'artifacts/font-groups/00_fonts/HUD/hud_action_font_z/Texture2D_4.tga').convert('RGBA')
    assert len(glyphs) == 256
    rows = []
    for g in glyphs:
        u, v, w, h, page = [g.get(k, 0) for k in ('StartU', 'StartV', 'USize', 'VSize', 'TextureIndex')]
        assert page == 0
        box = atlas.crop((u, v, u+w, v+h)).getchannel('A').point(lambda a: 255 if a > 64 else 0).getbbox() if w and h else None
        rows.append('    {' + ', '.join(map(str, box or (0, 0, 0, 0))) + '},')
    (root / 'src/hud_ink_bounds.h').write_text('// Generated by tools/prepare_hud_ink_bounds.py from the local retail font.\n#pragma once\n#include <array>\n#include <cstdint>\nnamespace aot {\ninline constexpr std::array<std::array<int16_t, 4>, 256> hud_ink_bounds{{\n' + '\n'.join(rows) + '\n}};\n}\n')

if __name__ == '__main__':
    main()
