"""Encode CC0 keyboard glyph alpha masks as native canvas rectangles.

The exact PNG alpha values are retained. Equal runs on adjacent scanlines are
merged so the game can draw these glyphs without creating platform textures.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
glyphs = {65: 'keyboard_e_outline', 66: 'keyboard_f_outline', 88: 'keyboard_r_outline',
          89: 'keyboard_space_icon_outline', 62: 'keyboard_escape_outline',
          58: 'keyboard_z_outline', 60: 'keyboard_z_outline',
          93: 'mouse_right_outline', 119: 'mouse_right_outline',
          94: 'mouse_left_outline', 120: 'mouse_left_outline',
          95: 'keyboard_q_outline', 121: 'keyboard_q_outline',
          96: 'keyboard_tab_outline', 122: 'keyboard_tab_outline',
          104: 'mouse_scroll_outline', 105: 'mouse_move',
          106: 'keyboard_c_outline', 107: 'keyboard_wasd',
          109: 'keyboard_arrow_up_outline', 111: 'keyboard_arrow_right_outline',
          113: 'keyboard_arrow_down_outline', 115: 'keyboard_arrow_left_outline'}


def source_image(name):
    if name != 'keyboard_wasd':
        return Image.open(root / 'resources/input' / (name + '.png')).convert('RGBA')
    # Preserve the source pixels, arranging W above A/S/D as on the keyboard.
    keys = [source_image('keyboard_' + key + '_outline') for key in 'wasd']
    keys = [key.crop(key.getbbox()) for key in keys]
    width, height = max(key.width for key in keys), max(key.height for key in keys)
    image = Image.new('RGBA', (3 * width + 4, 2 * height + 2))
    for key, (column, row) in zip(keys, [(1, 0), (0, 1), (1, 1), (2, 1)]):
        image.alpha_composite(key, (column * (width + 2), row * (height + 2)))
    return image

def rectangles(image):
    image = image.crop(image.getbbox())
    alpha = image.getchannel('A')
    result, active = [], {}
    for y in range(image.height):
        row, x = {}, 0
        while x < image.width:
            start, value = x, alpha.getpixel((x, y))
            x += 1
            while x < image.width and alpha.getpixel((x, y)) == value: x += 1
            if value:
                key = (start, x - start, value)
                index = active.get(key)
                if index is None:
                    index = len(result); result.append([start, y, x - start, 0, value])
                result[index][3] += 1
                row[key] = index
        active = row
    return image.width, image.height, result

def main():
    lines = ['// Generated by tools/prepare_keyboard_glyphs.py from Kenney CC0 input prompts.',
             '#pragma once', 'namespace aot {',
             'struct GlyphRect { unsigned char x, y, width, height, alpha; };',
             'struct KeyboardGlyph { unsigned char code, width, height; unsigned offset, count; };',
             'inline constexpr GlyphRect keyboard_rects[] = {']
    entries, count = [], 0
    shapes = {}
    for code, name in glyphs.items():
        if name in shapes:
            width, height, offset, size = shapes[name]
            entries.append(f'  {{{code},{width},{height},{offset},{size}}},')
            continue
        image = source_image(name)
        assert all((r, g, b) == (255, 255, 255) for r, g, b, a in image.getdata() if a)
        width, height, rects = rectangles(image)
        for rect in rects: lines.append('  {' + ','.join(map(str, rect)) + '},')
        entries.append(f'  {{{code},{width},{height},{count},{len(rects)}}},')
        shapes[name] = width, height, count, len(rects)
        print(f'{name}: {len(rects)} rectangles')
        count += len(rects)
    lines += ['};', 'inline constexpr KeyboardGlyph keyboard_glyphs[] = {', *entries, '};', '}']
    (root / 'src/keyboard_glyphs.generated.h').write_text('\n'.join(lines) + '\n')

if __name__ == '__main__': main()
